
name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: self-hosted
    
    strategy: 
      matrix:
        node-version: [17.x]
            
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: npm client
        working-directory: ./client
        run: npm install
      - name: npm root
        run: npm install
      - run: npm run build --if-present
