
name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: self-hosted
    env:
      VUE_APP_APIBASEURL: https://ec2-54-167-36-58.compute-1.amazonaws.com:443
      UI_KEY: ${{ secrets.SVM_UI_KEY }}
      UI_CERT: ${{ secrets.SVM_UI_CERT }}
    
    strategy: 
      matrix:
        node-version: [16.x]
            
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: pm2 restart app
