name: Push-to-EC2

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-54-211-238-3.compute-1.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/smart-vending-machine-ui"
